// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using feat.ingestion.Data;

#nullable disable

namespace feat.ingestion.Migrations
{
    [DbContext(typeof(IngestionDbContext))]
    [Migration("20251124104658_du-foundation-year")]
    partial class dufoundationyear
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("feat.common.Models.Employer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("ContactName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Url")
                        .HasMaxLength(2083)
                        .HasColumnType("nvarchar(2083)");

                    b.HasKey("Id");

                    b.ToTable("Employer");
                });

            modelBuilder.Entity("feat.common.Models.EmployerLocation", b =>
                {
                    b.Property<Guid>("EmployerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("EmployerId", "LocationId");

                    b.HasIndex("LocationId");

                    b.ToTable("EmployerLocation");
                });

            modelBuilder.Entity("feat.common.Models.Entry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AimOrAltTitle")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("AttendancePattern")
                        .HasColumnType("int");

                    b.Property<int?>("CourseType")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntryRequirements")
                        .HasMaxLength(2083)
                        .HasColumnType("nvarchar(2083)");

                    b.Property<bool>("FlexibleStart")
                        .HasColumnType("bit");

                    b.Property<int?>("IngestionState")
                        .HasColumnType("int");

                    b.Property<int?>("Level")
                        .HasColumnType("int");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("SecondaryReference")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("SourceReference")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("SourceSystem")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SourceUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int?>("StudyTime")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2083)
                        .HasColumnType("nvarchar(2083)")
                        .HasColumnName("URL");

                    b.Property<string>("WhatYouWillLearn")
                        .HasMaxLength(2083)
                        .HasColumnType("nvarchar(2083)");

                    b.HasKey("Id");

                    b.HasIndex("ProviderId");

                    b.ToTable("Entry");
                });

            modelBuilder.Entity("feat.common.Models.EntryCost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("EntryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("SourceSystem")
                        .HasColumnType("int");

                    b.Property<double?>("Value")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("EntryId");

                    b.ToTable("EntryCost");
                });

            modelBuilder.Entity("feat.common.Models.EntryInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<long?>("Duration")
                        .HasColumnType("bigint");

                    b.Property<Guid>("EntryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("SourceReference")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("SourceSystem")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("StudyMode")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EntryId");

                    b.HasIndex("LocationId");

                    b.ToTable("EntryInstance");
                });

            modelBuilder.Entity("feat.common.Models.EntrySector", b =>
                {
                    b.Property<Guid>("EntryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SectorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("SourceSystem")
                        .HasColumnType("int");

                    b.HasKey("EntryId", "SectorId");

                    b.HasIndex("SectorId");

                    b.ToTable("EntrySector");
                });

            modelBuilder.Entity("feat.common.Models.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address1")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Address2")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Address3")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Address4")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("County")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<Point>("GeoLocation")
                        .HasColumnType("geography");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Postcode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("SourceReference")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("SourceSystem")
                        .HasColumnType("int");

                    b.Property<string>("Telephone")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Town")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Url")
                        .HasMaxLength(2083)
                        .HasColumnType("nvarchar(2083)");

                    b.HasKey("Id");

                    b.ToTable("Location");
                });

            modelBuilder.Entity("feat.common.Models.PostcodeLatLong", b =>
                {
                    b.Property<string>("Postcode")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.HasKey("Postcode");

                    b.ToTable("postcodelatlng");
                });

            modelBuilder.Entity("feat.common.Models.Provider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("LegalEntityName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("OtherNames")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Pubukprn")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PUBUKPRN");

                    b.Property<string>("SourceReference")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("SourceSystem")
                        .HasColumnType("int");

                    b.Property<string>("TradingName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Ukprn")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UKPRN");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Provider");
                });

            modelBuilder.Entity("feat.common.Models.ProviderLocation", b =>
                {
                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("SourceSystem")
                        .HasColumnType("int");

                    b.HasKey("ProviderId", "LocationId");

                    b.HasIndex("LocationId");

                    b.ToTable("ProviderLocation");
                });

            modelBuilder.Entity("feat.common.Models.Sector", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("SourceSystem")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Sector");
                });

            modelBuilder.Entity("feat.common.Models.UniversityCourse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EntryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("Foundation")
                        .HasColumnType("bit");

                    b.Property<bool?>("Honours")
                        .HasColumnType("bit");

                    b.Property<bool?>("Nhs")
                        .HasColumnType("bit");

                    b.Property<bool?>("Sandwich")
                        .HasColumnType("bit");

                    b.Property<bool?>("YearAbroad")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("EntryId");

                    b.ToTable("UniversityCourse");
                });

            modelBuilder.Entity("feat.common.Models.Vacancy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ClosingDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EmployerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EntryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("HoursPerWeek")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Level")
                        .HasColumnType("int");

                    b.Property<bool?>("NationalVacancy")
                        .HasColumnType("bit");

                    b.Property<string>("NationalVacancyDetails")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<short?>("Positions")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("PostedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Url")
                        .HasMaxLength(2083)
                        .HasColumnType("nvarchar(2083)");

                    b.Property<decimal?>("Wage")
                        .HasColumnType("money");

                    b.Property<int?>("WageType")
                        .HasColumnType("int");

                    b.Property<int?>("WageUnit")
                        .HasColumnType("int");

                    b.Property<string>("WorkingWeekDescription")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("EmployerId");

                    b.HasIndex("EntryId");

                    b.ToTable("Vacancy");
                });

            modelBuilder.Entity("feat.ingestion.Models.DU.Aim", b =>
                {
                    b.Property<int>("AimCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AimCode"));

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("AimCode");

                    b.ToTable("DU_Aims");
                });

            modelBuilder.Entity("feat.ingestion.Models.DU.Course", b =>
                {
                    b.Property<int>("UKPRN")
                        .HasColumnType("int");

                    b.Property<string>("CourseId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("StudyMode")
                        .HasColumnType("int");

                    b.Property<int?>("Aim")
                        .HasColumnType("int");

                    b.Property<string>("AssessmentUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("CostsUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("CourseUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool?>("DistanceLearning")
                        .HasColumnType("bit");

                    b.Property<int?>("FoundationYear")
                        .HasColumnType("int");

                    b.Property<int?>("Hecos")
                        .HasColumnType("int");

                    b.Property<int?>("Hecos2")
                        .HasColumnType("int");

                    b.Property<int?>("Hecos3")
                        .HasColumnType("int");

                    b.Property<int?>("Hecos4")
                        .HasColumnType("int");

                    b.Property<int?>("Hecos5")
                        .HasColumnType("int");

                    b.Property<bool?>("Honours")
                        .HasColumnType("bit");

                    b.Property<string>("LearningUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool?>("NHS")
                        .HasColumnType("bit");

                    b.Property<int?>("NumberOfYears")
                        .HasColumnType("int");

                    b.Property<bool?>("Sandwich")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool?>("YearAbroad")
                        .HasColumnType("bit");

                    b.HasKey("UKPRN", "CourseId", "StudyMode");

                    b.ToTable("DU_Courses");
                });

            modelBuilder.Entity("feat.ingestion.Models.DU.IngestionState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("DownloadComplete")
                        .HasColumnType("bit");

                    b.Property<string>("ETag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Extracted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("DU_IngestionState");
                });

            modelBuilder.Entity("feat.ingestion.Models.DU.Institution", b =>
                {
                    b.Property<int>("UKPRN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UKPRN"));

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("Country")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("OtherNames")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("StudentUnionUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Telephone")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TradingName")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Url")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("UKPRN");

                    b.ToTable("DU_Institutions");
                });

            modelBuilder.Entity("feat.ingestion.Models.DU.Location", b =>
                {
                    b.Property<int>("UKPRN")
                        .HasColumnType("int");

                    b.Property<string>("LocationId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("AccommodationUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Country")
                        .HasColumnType("int");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("StudentUnionUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("UKPRN", "LocationId");

                    b.ToTable("DU_Locations");
                });

            modelBuilder.Entity("feat.ingestion.Models.FAA.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressLine1")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AddressLine3")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AddressLine4")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ApprenticeshipId")
                        .HasColumnType("int");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Postcode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("ApprenticeshipId");

                    b.ToTable("FAA_Addresses");
                });

            modelBuilder.Entity("feat.ingestion.Models.FAA.Apprenticeship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("ApprenticeshipLevel")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ClosingDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CourseLarsCode")
                        .HasColumnType("int");

                    b.Property<int>("CourseLevel")
                        .HasColumnType("int");

                    b.Property<string>("CourseRoute")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CourseTitle")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CourseType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<double?>("Distance")
                        .HasColumnType("float");

                    b.Property<string>("EmployerContactEmail")
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("EmployerContactName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EmployerContactPhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("EmployerName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EmployerWebsiteUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("ExpectedDuration")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("HoursPerWeek")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsDisabilityConfident")
                        .HasColumnType("bit");

                    b.Property<bool>("IsNationalVacancy")
                        .HasColumnType("bit");

                    b.Property<string>("IsNationalVacancyDetails")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("NumberOfPositions")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("PostedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProviderName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Ukprn")
                        .HasColumnType("int");

                    b.Property<string>("VacancyReference")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("VacancyUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("WageAdditionalInformation")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<double?>("WageAmount")
                        .HasColumnType("float");

                    b.Property<string>("WageType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("WageUnit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("WorkingWeekDescription")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.ToTable("FAA_Apprenticeships");
                });

            modelBuilder.Entity("feat.ingestion.Models.FAC.AimData", b =>
                {
                    b.Property<string>("LearnAimRef")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("AwardOrgCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LearnAimRefTitle")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("NotionalNVQLevelv2")
                        .HasColumnType("int");

                    b.HasKey("LearnAimRef");

                    b.ToTable("FAC_AimData");
                });

            modelBuilder.Entity("feat.ingestion.Models.FAC.AllCoursesCourse", b =>
                {
                    b.Property<Guid>("COURSE_ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("COURSE_RUN_ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("ATTENDANCE_PATTERN")
                        .HasColumnType("int");

                    b.Property<string>("AWARDING_BODY")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal?>("COST")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("COST_DESCRIPTION")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("COURSE_NAME")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("COURSE_TYPE")
                        .HasColumnType("int");

                    b.Property<string>("COURSE_URL")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("CREATED_DATE")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DELIVER_MODE")
                        .HasColumnType("int");

                    b.Property<long?>("DURATION")
                        .HasColumnType("bigint");

                    b.Property<int?>("EDUCATION_LEVEL")
                        .HasColumnType("int");

                    b.Property<string>("ENTRY_REQUIREMENTS")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<bool?>("FLEXIBLE_STARTDATE")
                        .HasColumnType("bit");

                    b.Property<string>("HOW_YOU_WILL_BE_ASSESSED")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("LEARN_AIM_REF")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<Point>("LOCATION")
                        .HasColumnType("geography");

                    b.Property<string>("LOCATION_ADDRESS1")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("LOCATION_ADDRESS2")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("LOCATION_COUNTY")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("LOCATION_EMAIL")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("LOCATION_NAME")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("LOCATION_POSTCODE")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("LOCATION_TELEPHONE")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("LOCATION_TOWN")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("LOCATION_WEBSITE")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool?>("NATIONAL")
                        .HasColumnType("bit");

                    b.Property<string>("PROVIDER_NAME")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("PROVIDER_UKPRN")
                        .HasColumnType("int");

                    b.PrimitiveCollection<string>("REGIONS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SECTOR")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("STARTDATE")
                        .HasColumnType("datetime2");

                    b.Property<int?>("STUDY_MODE")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UPDATED_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("WHO_THIS_COURSE_IS_FOR")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.HasKey("COURSE_ID", "COURSE_RUN_ID");

                    b.ToTable("FAC_AllCourses");
                });

            modelBuilder.Entity("feat.ingestion.Models.FAC.ApprovedQualification", b =>
                {
                    b.Property<string>("QualificationNumber")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<bool>("AdvancedLearnerLoans_FundingAvailable")
                        .HasColumnType("bit");

                    b.Property<bool>("Age1416_FundingAvailable")
                        .HasColumnType("bit");

                    b.Property<bool>("Age1619_FundingAvailable")
                        .HasColumnType("bit");

                    b.Property<bool>("DigitalEntitlement_FundingAvailable")
                        .HasColumnType("bit");

                    b.Property<bool>("FreeCoursesForJobs_FundingAvailable")
                        .HasColumnType("bit");

                    b.Property<bool>("LegalEntitlementEnglishandMaths_FundingAvailable")
                        .HasColumnType("bit");

                    b.Property<bool>("LegalEntitlementL2L3_FundingAvailable")
                        .HasColumnType("bit");

                    b.Property<int?>("Level")
                        .HasColumnType("int");

                    b.Property<bool>("LifelongLearningEntitlement_FundingAvailable")
                        .HasColumnType("bit");

                    b.Property<bool>("LocalFlexibilities_FundingAvailable")
                        .HasColumnType("bit");

                    b.Property<int?>("QualificationType")
                        .HasColumnType("int");

                    b.Property<string>("SectorSubjectArea")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("QualificationNumber");

                    b.ToTable("FAC_ApprovedQualifications");
                });

            modelBuilder.Entity("feat.ingestion.Models.FAC.Course", b =>
                {
                    b.Property<Guid>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AwardingBody")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CourseDescription")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("CourseStatus")
                        .HasColumnType("int");

                    b.Property<int?>("CourseType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EducationLevel")
                        .HasColumnType("int");

                    b.Property<string>("EntryRequirements")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("HowYoullBeAssessed")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("HowYoullLearn")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("LearnAimRef")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<int>("ProviderUkprn")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("WhatYoullLearn")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("WhatYoullNeed")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("WhereNext")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.HasKey("CourseId");

                    b.ToTable("FAC_Courses");
                });

            modelBuilder.Entity("feat.ingestion.Models.FAC.CourseRun", b =>
                {
                    b.Property<Guid>("CourseRunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("AttendancePattern")
                        .HasColumnType("int");

                    b.Property<decimal?>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CostDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CourseRunStatus")
                        .HasColumnType("int");

                    b.Property<string>("CourseWebsite")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeliveryMode")
                        .HasColumnType("int");

                    b.Property<long?>("Duration")
                        .HasColumnType("bigint");

                    b.Property<bool>("FlexibleStartDate")
                        .HasColumnType("bit");

                    b.Property<bool>("National")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("StudyMode")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("VenueId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CourseRunId");

                    b.ToTable("FAC_CourseRuns");
                });

            modelBuilder.Entity("feat.ingestion.Models.FAC.Provider", b =>
                {
                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Alias")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CourseDirectoryName")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ProviderName")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("ProviderStatus")
                        .HasColumnType("int");

                    b.Property<int?>("ProviderType")
                        .HasColumnType("int");

                    b.Property<string>("TradingName")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("Ukprn")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("ProviderId");

                    b.ToTable("FAC_Providers");
                });

            modelBuilder.Entity("feat.ingestion.Models.FAC.TLevel", b =>
                {
                    b.Property<Guid>("TLevelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("EntryRequirements")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("HowYoullBeAssessed")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("HowYoullLearn")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TLevelDefinitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TLevelStatus")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Website")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("WhatYouCanDoNext")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("WhatYoullLearn")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("WhoFor")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.HasKey("TLevelId");

                    b.ToTable("FAC_TLevels");
                });

            modelBuilder.Entity("feat.ingestion.Models.FAC.TLevelDefinition", b =>
                {
                    b.Property<Guid>("TLevelDefinitionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("QualificationLevel")
                        .HasColumnType("int");

                    b.HasKey("TLevelDefinitionId");

                    b.ToTable("FAC_TLevelDefinitions");
                });

            modelBuilder.Entity("feat.ingestion.Models.FAC.TLevelLocation", b =>
                {
                    b.Property<Guid>("TLevelLocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TLevelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("TLevelLocationStatus")
                        .HasColumnType("int");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TLevelLocationId");

                    b.ToTable("FAC_TLevelLocations");
                });

            modelBuilder.Entity("feat.ingestion.Models.FAC.Venue", b =>
                {
                    b.Property<Guid>("VenueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AddressLine1")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("County")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Postcode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<Guid?>("ProviderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("ProviderUkprn")
                        .HasColumnType("int");

                    b.Property<string>("Telephone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Town")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("VenueName")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("VenueStatus")
                        .HasColumnType("int");

                    b.Property<string>("Website")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("VenueId");

                    b.ToTable("FAC_Venues");
                });

            modelBuilder.Entity("feat.common.Models.EmployerLocation", b =>
                {
                    b.HasOne("feat.common.Models.Employer", "Employer")
                        .WithMany("EmployerLocations")
                        .HasForeignKey("EmployerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("feat.common.Models.Location", "Location")
                        .WithMany("EmployerLocations")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employer");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("feat.common.Models.Entry", b =>
                {
                    b.HasOne("feat.common.Models.Provider", "Provider")
                        .WithMany("Entries")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("feat.common.Models.EntryCost", b =>
                {
                    b.HasOne("feat.common.Models.Entry", "Entry")
                        .WithMany("EntryCosts")
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entry");
                });

            modelBuilder.Entity("feat.common.Models.EntryInstance", b =>
                {
                    b.HasOne("feat.common.Models.Entry", "Entry")
                        .WithMany("EntryInstances")
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("feat.common.Models.Location", "Location")
                        .WithMany("EntryInstances")
                        .HasForeignKey("LocationId");

                    b.Navigation("Entry");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("feat.common.Models.EntrySector", b =>
                {
                    b.HasOne("feat.common.Models.Entry", "Entry")
                        .WithMany("EntrySectors")
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("feat.common.Models.Sector", "Sector")
                        .WithMany("EntrySectors")
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entry");

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("feat.common.Models.ProviderLocation", b =>
                {
                    b.HasOne("feat.common.Models.Location", "Location")
                        .WithMany("ProviderLocations")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("feat.common.Models.Provider", "Provider")
                        .WithMany("ProviderLocations")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("feat.common.Models.UniversityCourse", b =>
                {
                    b.HasOne("feat.common.Models.Entry", "Entry")
                        .WithMany("UniversityCourses")
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entry");
                });

            modelBuilder.Entity("feat.common.Models.Vacancy", b =>
                {
                    b.HasOne("feat.common.Models.Employer", "Employer")
                        .WithMany("Vacancies")
                        .HasForeignKey("EmployerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("feat.common.Models.Entry", "Entry")
                        .WithMany("Vacancies")
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employer");

                    b.Navigation("Entry");
                });

            modelBuilder.Entity("feat.ingestion.Models.FAA.Address", b =>
                {
                    b.HasOne("feat.ingestion.Models.FAA.Apprenticeship", "Apprenticeship")
                        .WithMany("Addresses")
                        .HasForeignKey("ApprenticeshipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Apprenticeship");
                });

            modelBuilder.Entity("feat.common.Models.Employer", b =>
                {
                    b.Navigation("EmployerLocations");

                    b.Navigation("Vacancies");
                });

            modelBuilder.Entity("feat.common.Models.Entry", b =>
                {
                    b.Navigation("EntryCosts");

                    b.Navigation("EntryInstances");

                    b.Navigation("EntrySectors");

                    b.Navigation("UniversityCourses");

                    b.Navigation("Vacancies");
                });

            modelBuilder.Entity("feat.common.Models.Location", b =>
                {
                    b.Navigation("EmployerLocations");

                    b.Navigation("EntryInstances");

                    b.Navigation("ProviderLocations");
                });

            modelBuilder.Entity("feat.common.Models.Provider", b =>
                {
                    b.Navigation("Entries");

                    b.Navigation("ProviderLocations");
                });

            modelBuilder.Entity("feat.common.Models.Sector", b =>
                {
                    b.Navigation("EntrySectors");
                });

            modelBuilder.Entity("feat.ingestion.Models.FAA.Apprenticeship", b =>
                {
                    b.Navigation("Addresses");
                });
#pragma warning restore 612, 618
        }
    }
}
