// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using feat.ingestion.Data;

#nullable disable

namespace feat.ingestion.Migrations
{
    [DbContext(typeof(IngestionDbContext))]
    [Migration("20251021091536_AddAllCoursesStagingTable")]
    partial class AddAllCoursesStagingTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("feat.common.Models.Employer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Employer");
                });

            modelBuilder.Entity("feat.common.Models.EmployerLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EmployerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EmployerId");

                    b.HasIndex("LocationId");

                    b.ToTable("EmployerLocation");
                });

            modelBuilder.Entity("feat.common.Models.Entry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("AttendancePattern")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntryRequirements")
                        .HasMaxLength(2083)
                        .HasColumnType("nvarchar(2083)");

                    b.Property<bool>("FlexibleStart")
                        .HasColumnType("bit");

                    b.Property<int?>("Level")
                        .HasColumnType("int");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("SecondaryReference")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("SourceSystem")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SourceUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2083)
                        .HasColumnType("nvarchar(2083)")
                        .HasColumnName("URL");

                    b.HasKey("Id");

                    b.HasIndex("ProviderId");

                    b.ToTable("Entry");
                });

            modelBuilder.Entity("feat.common.Models.EntryCost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("EntryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("Value")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("EntryId");

                    b.ToTable("EntryCost");
                });

            modelBuilder.Entity("feat.common.Models.EntryInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("time");

                    b.Property<Guid>("EntryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("StudyMode")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EntryId");

                    b.ToTable("EntryInstance");
                });

            modelBuilder.Entity("feat.common.Models.EntryLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EntryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EntryId");

                    b.HasIndex("LocationId");

                    b.ToTable("EntryLocation");
                });

            modelBuilder.Entity("feat.common.Models.EntrySector", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EntryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SectorId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EntryId");

                    b.HasIndex("SectorId");

                    b.ToTable("EntrySector");
                });

            modelBuilder.Entity("feat.common.Models.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address1")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Address2")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Address3")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Address4")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("County")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<Point>("GeoLocation")
                        .HasColumnType("geography");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Postcode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Telephone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Town")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Url")
                        .HasMaxLength(2083)
                        .HasColumnType("nvarchar(2083)");

                    b.HasKey("Id");

                    b.ToTable("Location");
                });

            modelBuilder.Entity("feat.common.Models.Provider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("LegalEntityName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("OtherNames")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Pubukprn")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PUBUKPRN");

                    b.Property<string>("TradingName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Ukprn")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UKPRN");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Provider");
                });

            modelBuilder.Entity("feat.common.Models.ProviderLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("ProviderId");

                    b.ToTable("ProviderLocation");
                });

            modelBuilder.Entity("feat.common.Models.Sector", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Sector");
                });

            modelBuilder.Entity("feat.common.Models.Staging.FAC.AllCoursesCourse", b =>
                {
                    b.Property<Guid>("COURSE_ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("COURSE_RUN_ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("ATTENDANCE_PATTERN")
                        .HasColumnType("int");

                    b.Property<string>("AWARDING_BODY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("COST")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("COST_DESCRIPTION")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("COURSE_NAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("COURSE_TYPE")
                        .HasColumnType("int");

                    b.Property<string>("COURSE_URL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CREATED_DATE")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DELIVER_MODE")
                        .HasColumnType("int");

                    b.Property<TimeSpan?>("DURATION")
                        .HasColumnType("time");

                    b.Property<int?>("EDUCATION_LEVEL")
                        .HasColumnType("int");

                    b.Property<string>("ENTRY_REQUIREMENTS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("FLEXIBLE_STARTDATE")
                        .HasColumnType("bit");

                    b.Property<string>("HOW_YOU_WILL_BE_ASSESSED")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LEARN_AIM_REF")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Point>("LOCATION")
                        .HasColumnType("geography");

                    b.Property<string>("LOCATION_ADDRESS1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LOCATION_ADDRESS2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LOCATION_COUNTY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LOCATION_EMAIL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LOCATION_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LOCATION_POSTCODE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LOCATION_TELEPHONE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LOCATION_TOWN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LOCATION_WEBSITE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("NATIONAL")
                        .HasColumnType("bit");

                    b.Property<string>("PROVIDER_NAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PROVIDER_UKPRN")
                        .HasColumnType("int");

                    b.PrimitiveCollection<string>("REGIONS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SECTOR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("STARTDATE")
                        .HasColumnType("datetime2");

                    b.Property<int?>("STUDY_MODE")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UPDATED_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("WHO_THIS_COURSE_IS_FOR")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("COURSE_ID", "COURSE_RUN_ID");

                    b.ToTable("Staging_AllCourses");
                });

            modelBuilder.Entity("feat.common.Models.UniversityCourse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EntryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("Foundation")
                        .HasColumnType("bit");

                    b.Property<bool?>("Honours")
                        .HasColumnType("bit");

                    b.Property<bool?>("Nhs")
                        .HasColumnType("bit");

                    b.Property<bool?>("Sandwich")
                        .HasColumnType("bit");

                    b.Property<bool?>("YearAbroad")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("EntryId");

                    b.ToTable("UniversityCourse");
                });

            modelBuilder.Entity("feat.common.Models.Vacancy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ClosingDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EmployerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EntryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("HoursPerWeek")
                        .HasColumnType("int");

                    b.Property<short?>("Positions")
                        .HasColumnType("smallint");

                    b.Property<decimal?>("Wage")
                        .HasColumnType("money");

                    b.Property<int?>("WageUnit")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployerId");

                    b.HasIndex("EntryId");

                    b.ToTable("Vacancy");
                });

            modelBuilder.Entity("feat.common.Models.EmployerLocation", b =>
                {
                    b.HasOne("feat.common.Models.Employer", "Employer")
                        .WithMany("EmployerLocations")
                        .HasForeignKey("EmployerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("feat.common.Models.Location", "Location")
                        .WithMany("EmployerLocations")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employer");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("feat.common.Models.Entry", b =>
                {
                    b.HasOne("feat.common.Models.Provider", "Provider")
                        .WithMany("Entries")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("feat.common.Models.EntryCost", b =>
                {
                    b.HasOne("feat.common.Models.Entry", "Entry")
                        .WithMany("EntryCosts")
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entry");
                });

            modelBuilder.Entity("feat.common.Models.EntryInstance", b =>
                {
                    b.HasOne("feat.common.Models.Entry", "Entry")
                        .WithMany("EntryInstances")
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entry");
                });

            modelBuilder.Entity("feat.common.Models.EntryLocation", b =>
                {
                    b.HasOne("feat.common.Models.Entry", "Entry")
                        .WithMany("EntryLocations")
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("feat.common.Models.Location", "Location")
                        .WithMany("EntryLocations")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entry");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("feat.common.Models.EntrySector", b =>
                {
                    b.HasOne("feat.common.Models.Entry", "Entry")
                        .WithMany("EntrySectors")
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("feat.common.Models.Sector", "Sector")
                        .WithMany("EntrySectors")
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entry");

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("feat.common.Models.ProviderLocation", b =>
                {
                    b.HasOne("feat.common.Models.Location", "Location")
                        .WithMany("ProviderLocations")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("feat.common.Models.Provider", "Provider")
                        .WithMany("ProviderLocations")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("feat.common.Models.UniversityCourse", b =>
                {
                    b.HasOne("feat.common.Models.Entry", "Entry")
                        .WithMany("UniversityCourses")
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entry");
                });

            modelBuilder.Entity("feat.common.Models.Vacancy", b =>
                {
                    b.HasOne("feat.common.Models.Employer", "Employer")
                        .WithMany("Vacancies")
                        .HasForeignKey("EmployerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("feat.common.Models.Entry", "Entry")
                        .WithMany("Vacancies")
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employer");

                    b.Navigation("Entry");
                });

            modelBuilder.Entity("feat.common.Models.Employer", b =>
                {
                    b.Navigation("EmployerLocations");

                    b.Navigation("Vacancies");
                });

            modelBuilder.Entity("feat.common.Models.Entry", b =>
                {
                    b.Navigation("EntryCosts");

                    b.Navigation("EntryInstances");

                    b.Navigation("EntryLocations");

                    b.Navigation("EntrySectors");

                    b.Navigation("UniversityCourses");

                    b.Navigation("Vacancies");
                });

            modelBuilder.Entity("feat.common.Models.Location", b =>
                {
                    b.Navigation("EmployerLocations");

                    b.Navigation("EntryLocations");

                    b.Navigation("ProviderLocations");
                });

            modelBuilder.Entity("feat.common.Models.Provider", b =>
                {
                    b.Navigation("Entries");

                    b.Navigation("ProviderLocations");
                });

            modelBuilder.Entity("feat.common.Models.Sector", b =>
                {
                    b.Navigation("EntrySectors");
                });
#pragma warning restore 612, 618
        }
    }
}
