env                = "Dev"
product            = "Find Education and Training"
prefix             = "s213d01"
location           = "westeurope"
api_image          = "s213d01acr.azurecr.io/feat-api:latest"
website_image      = "s213d01sacr.azurecr.io/feat-web:latest"