env                = "Test"
product            = "Find Education and Training"
prefix             = "s213t01"
location           = "westeurope"
api_image          = "s213t01acr.azurecr.io/feat-api:latest"
website_image      = "s213t01sacr.azurecr.io/feat-web:latest"