env                = "Test"
product            = "Find Education and Training"
prefix             = "s265t02"
location           = "uksouth"
api_image_name     = "feat-api:latest"
website_image_name = "feat-web:latest"
google_tag_manager = ""
clarity            = ""