name: Deploy Azure Infrastructure

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment"
        required: true
        type: choice
        options:
          - development
          - test

jobs:
  terraform:
    name: "Deploy"
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    defaults:
      run:
        working-directory: infrastructure/terraform

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4

      - name: "Setup Terraform"
        uses: hashicorp/setup-terraform@v3

      - name: "Azure Login"
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: "Terraform Init"
        run: terraform init

      - name: "Terraform Plan"
        run: terraform plan -var-file=${{ github.event.inputs.environment }}.tfvars

      - name: "Terraform Apply"
        run: terraform apply -auto-approve -var-file=${{ github.event.inputs.environment }}.tfvars
