name: Generate - Terraform Documentation

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  pull_request: 
    paths: [ "infrastructure/terraform/**", "**/generate-tf-docs.yml" ]

jobs:
  docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Generate TF Documentation and push
        uses: terraform-docs/gh-actions@v1.4.1
        with:
          working-dir: "infrastructure/terraform"
          output-method: replace
          git-push: 'true'
          
      - name: Commit and Push Documentation
        run: |
          git config --global user.name "Documentation Bot"
          git config --global user.email "documentation-bot-bot@users.noreply.github.com"
          git commit -am "Update documentation"
          git push
        continue-on-error: true

