name: Generate - Terraform Documentation

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  pull_request: 
    paths: [ "infrastructure/terraform/**", "**/generate-tf-docs.yml" ]

jobs:
  docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Generate TF Documentation and push
        uses: terraform-docs/gh-actions@v1.4.1
        with:
          find-dir: infrastructure
          output-file: docs/architecture/terraform.md
          output-method: replace
          git-push: "true"
